### ISSUE TITLE
feat: 성능 측정 결과 파일로 만들기

### ISSUE THREAD

**Issue by cndqjacndqja** [sogorae/jpa-query-counter#1]
## as-is
쿼리 카운팅 결과를 로그로 남기고 있어서, 테스트를 돌린다면 url을 보며 하나하나 찾아야 한다.

## to-be
쿼리 카운팅 결과를 API 호출에 따라 보고서 형태로 정리하여, 파일을 만들어 낸다.

**Comment by sojukang** [comment]
Junit의 경우  html 형식으로 보기 좋게 문서화 해주는데, 리포트 형식으로 만들면 좋을 것 같습니다.

**Comment by cndqjacndqja** [comment]
네 그것도 리팩토링하면서 추가해 보면 좋을 것 같아요.
html 형식으로 문서화 하는 것은 이슈를 따로 파도 좋을 것 같아요!
추가로 현재 파일에 저장되는 쿼리문의 형식이 갖춰져 있지 않은데, JPA에서의 format을 참고해 보면 좋을 것 같습니다. :)
