### ISSUE TITLE
feat: 적합한 인덱싱 추측하여 통계 추출

### ISSUE THREAD

**Issue by cndqjacndqja** [sogorae/jpa-query-counter#5]
앞으로 팀 프로젝트에서 인덱싱을 하게 될 텐데요.
원래는 API를 각각 확인해 보면서 판단하는 것 외에 방법이 떠오르지 않았지만
이 라이브러리를 통해, 어느 정도 자동화하는 방법도 있지 않을까요?
각 API 마다 어떤 인덱스 자료구조를 사용하고 있는지, 어떤 것을 기준으로 인덱싱을 하고 있는지에 대한 정보를 나타내도 좋을 것 같아요!

**Comment by sojukang** [comment]
그런데 인덱싱을 하이버네이트 측에서 알 수 있는 방법이 있을까요??

**Comment by cndqjacndqja** [comment]
DB 서버에 접근해서 어떤 인덱스를 탔는지 볼 수 있는 파일을 찾아 읽고, 분석하는 방식을 생각했는데요!
구현 방식이 너무 까다로울 것 같아서, 후순위로 두거나 고려하지 않는게 좋을 것 같네요 😅
